### ISSUE TITLE
explain tar_option_set(error = “null”) in the debugging chapter

### ISSUE THREAD

**Issue by wlandau** [ropensci-books/targets#64]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci-books/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci-books/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

**Comment by wlandau** [comment]
Done in the debugging chapter rewrite.

**Comment by CorradoLanera** [comment]
@wlandau , in the chapter you have mentioned: "This is especially helpful with [dynamic branching](https://books.ropensci.org/targets/dynamic.html)." 

Why/how? If a branch of a pattern returns an error, i.e., a `NULL` returned output, does the branch's parent pattern succeed in merging its other branches so that the children(s) can run? Maybe, it could be of high utility to include the information in the manual. I have experienced an 8k branches pattern in the middle of a pipeline, with 1 single error; I would love to simply "ignore" before/instead of go backward to find the CSV row in the source file with the affecting line and change my "data-raw" (or create an additional middle target with that line removed). Maybe I could correct the issue in the future, but now I need a final result that simply ignores that.
